spring.application.name=ApiGateway
server.port=9091



spring.cloud.gateway.server.webflux.routes[0].id=deptservice
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/dept/**
spring.cloud.gateway.server.webflux.routes[0].uri=lb://deptservice

spring.cloud.gateway.server.webflux.routes[1].id=employeeservice
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/emps/**
spring.cloud.gateway.server.webflux.routes[1].uri=lb://employeeservice